list_of_allergies = [
    {'name': 'sodium benzoate', 'id': 'sodium_benzoate'},
    {'name': 'benzoate', 'id': 'benzoate'},
    {'name': 'fish', 'id': 'fish'},
    {'name': 'shellfish', 'id': 'shellfish'},
    {'name': 'honey', 'id': 'honey'},
    {'name': 'xylitol', 'id': 'xylitol'},
    {'name': 'gluten', 'id': 'gluten'},
    {'name': 'eggs', 'id': 'eggs'},
    {'name': 'soybeans', 'id': 'soybeans'},
    {'name': 'wheat', 'id': 'wheat'},
    {'name': 'milk', 'id': 'milk'},
    {'name': 'peanuts', 'id': 'peanuts'},
    {'name': 'tree nut', 'id': 'tree_nut'},
    {'name': 'soy', 'id': 'soy'},
    {'name': 'linseed', 'id': 'linseed'},
    {'name': 'sesame seed', 'id': 'sesame_seed'},
    {'name': 'peach', 'id': 'peach'},
    {'name': 'banana', 'id': 'banana'},
    {'name': 'avocado', 'id': 'avocado'},
    {'name': 'kiwi fruit', 'id': 'kiwi_fruit'},
    {'name': 'passion fruit', 'id': 'passion_fruit'},
    {'name': 'celery', 'id': 'celery'},
    {'name': 'garlic', 'id': 'garlic'},
    {'name': 'mustard seeds', 'id': 'mustard seeds'},
    {'name': 'aniseed', 'id': 'aniseed'},
    {'name': 'chamomile', 'id': 'chamomile'},
]
